source 'https://ruby.taobao.org'

gem 'puma'
gem 'passenger'
gem 'unicorn'

gem 'rack'
gem 'activerecord'
gem 'pg'
gem 'httparty'


# remove following gems when you are using rbx
# for some reason these gems can't be installed
gem 'byebug'
gem 'thin'
