source 'https://ruby.taobao.org/'

gem 'eventmachine'
gem 'uuid'
gem 'cramp'

gem 'puma'
gem 'rack'
gem 'activerecord'
gem 'pg'


# remove following gems when you are using rbx
# for some reason these gems can't be installed
gem 'byebug'
gem 'thin'
